### ISSUE TITLE
Cannot Run OT

### ISSUE THREAD

**Issue by duramato** [flygoast/opentracker#3]
When trying to run im getting `No socket address for live sync specified.` and it just closes , this is while running the non debug. On debug i get 

```
Binding socket type TCP to address [0.0.0.0]:6969... success.
Binding socket type UDP to address [0.0.0.0]:6969... success.
installing 0 workers on udp socket -1
Dropping to user nobody.
No socket address for live sync specified.
```

which i dont think adds any other usefull info
Am i missing something?

**Comment by flygoast** [comment]
You should specify livesync configuration, such as:`livesync.cluster.listen 192.168.0.1:9696`

**Comment by duramato** [comment]
Is there a way to run OT without live sync ? Since im not running any other tracker

**Comment by flygoast** [comment]
No. At this version you must specify it. This is an unofficial version. I haven't looked up the official code too long. You can to check it whether it has changed it.
